logging:
  level:
    org:
      level:
        org:
          springframework:
            jdbc:
              core: TRACE

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/sns?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: new1234!
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379